# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node
      
    working_directory: ~/contracts

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install
          command: |
            npm install
            sudo npm install -g ganache-cli@beta

      # update cache if needed
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      # run rpc
      - run:
          name: Run test-rpc
          background: true
          command: |
            ganache-cli

      # run tests
      - run:
          name: Run test
          command: |
            npm test